[package]
name = "ada-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
simple_logger = "5.0.0"
uuid = { version = "1.2", features = ["v4"] }


[[bin]]
name = "client"
path = "src/client.rs"